#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum class WINMODE { FULL, WIN, END };
	enum class PROTOTYPE { GAMEOBJECT, COMPONENT };
	enum class COMPONENT { VIBUFFER, SHADER, TEXTURE, MODEL, END };
	enum class STATE { RIGHT, UP, LOOK, POSITION, END };
	enum class RENDERGROUP { PRIORITY, SHADOW, NONBLEND, NONLIGHT, BLEND, UI, END };
	enum class D3DTS { VIEW, PROJ, END };
	enum class DIMB { LBUTTON, RBUTTON, WHEEL, X, END };
	enum class DIMM { X, Y, WHEEL, END };
	enum class DIR { LEFT, RIGHT, UP, DOWN, END };
	enum class EQUIPBTN { NONE, X, Y, END };
	enum class MATERIAL { NONE, DIFFUSE, SPECULAR, AMBIENT, EMISSIVE, HEIGHT, NORMALS, SHININESS, METALLIC, ROUGHNESS, AO, END };
	enum class MODEL { NONANIM, SKINNED, END };
	enum class PART { BODY, WEAPON, EFFECT, ACCESSORY, END };
	enum class COLLIDER { AABB, OBB, SPHERE, END };
	enum class GROUP { PLAYER, SENSOR_PLAYER, WEAPON_PLAYER, SHIELD_PLAYER,
						MONSTER, SENSOR_MONSTER, WEAPON_MONSTER, SHIELD_MONSTER, ATTACK_WINDOW_MONSTER,
						NPC, TRIGGER,
						MAP, TRAP, BOUNDARY,
						MAP_OBJECT, ITEM, 
						WIND, END };
	enum class DEFERRED { DEBUG, DIRECTIONAL, POINT, COMBINED, END };
	enum class LIGHT { DIRECTIONAL, POINT, SPOT, END };
	enum class LIGHT_USAGE { STATIC, DYNAMIC, END };
	enum class BILLBOARD { NONE, AXIS, SCREEN, END };
	enum class BLEND { ALPHA, ADD, MULTIPLY, END };
	enum class SOUND { BGM, EFFECT, MAXCHANNEL };
}

#endif // Engine_Enum_h__